# Generated by Django 4.0.4 on 2022-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'verbose_name': 'Сословие', 'verbose_name_plural': 'Сословия'},
        ),
        migrations.AddField(
            model_name='citizen',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
