# Generated by Django 4.0.4 on 2022-07-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_citizen_options_citizen_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='subordinate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='citizens.citizen', verbose_name='Подчиненный'),
        ),
    ]
