# Generated by Django 4.0.4 on 2022-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_alter_citizen_subordinate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='subordinate',
            new_name='master',
        ),
    ]
