# Generated by Django 4.0.6 on 2022-07-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_rename_subordinate_citizen_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'ordering': ('-age',), 'verbose_name': 'Сословие', 'verbose_name_plural': 'Сословия'},
        ),
        migrations.AlterField(
            model_name='citizen',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citizens.citizen', verbose_name='Хозяин'),
        ),
    ]
