# Generated by Django 4.0.6 on 2022-07-12 18:38

import citizens.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_alter_citizen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(validators=[citizens.validators.validate_interval], verbose_name='Возраст'),
        ),
        migrations.AddConstraint(
            model_name='citizen',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 120)), name='age_gte_120'),
        ),
        migrations.AddConstraint(
            model_name='citizen',
            constraint=models.CheckConstraint(check=models.Q(('age__lte', 0)), name='age_lte_0'),
        ),
    ]
